name: Publish to ghcr.io

on:
  push:
    branches:
      - main
    tags:
      - v*
env:
  # Named after the repo by default
  IMAGE_NAME: ${{ github.repository }}

jobs:
  push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - name: Build image
        run: docker build . --file Dockerfile --tag $IMAGE_NAME --label "runnumber=${GITHUB_RUN_ID}"
      - name: Log into registry
        run: echo "${{ secrets.DOCKERHUB }}" | docker login -u bilts --password-stdin
      - name: Push image
        run: |
          IMAGE_ID=harmonyservices/$IMAGE_NAME

          # Ensure lowercase (does nothing in practice)
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')

          # For tagged versions, translate e.g. "refs/tags/v1.2.3" -> "1.2.3"
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')

          # For the main branch, use "latest" as the version
          [ "$VERSION" == "main" ] && VERSION=latest
          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION
          docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION